# Этап сборки
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Финальный образ
FROM node:20-alpine

WORKDIR /app

# Только необходимые файлы
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY package.json ./

ENV NODE_ENV=production

EXPOSE 3000
CMD ["node", "dist/main"]
